### ISSUE TITLE
Little doubt

### ISSUE THREAD

**Issue by ray1919** [aakechin/cutPrimers#2]
``` python
def makeHashes(seq,k):
    # k is the length of parts
    subSeqs=[]
    h=[]
    lens=set()
    for i in range(len(seq)-k+1):
        h.append(hashlib.md5(seq[i:i+k].encode('utf-8')).hexdigest())
        lens.add(k)
    return(h,lens)
```
I am new to python. Why add **k** to **set lens** in each iteration since it is a fixed value?

**Comment by aakechin** [comment]
Yes, you are right, it is an excess operation. I replaced it with one-time value storage in the function. Thank you for your comment!
